services:
  - type: web
    plan: free
    name: Auto-Approve-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/CodeXBots/Auto-Approve-bot.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: ADMIN
        sync: false
